In [1]:
import numpy as np

In [3]:
import numpy as np
list_ = [1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

##Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
Ans - Both variables are of the list data type, which is a mutable sequence of elements. This means that the elements of a list can be changed after the list is created. Lists can contain elements of any data type, including strings, integers, floats, and objects.

In [7]:
print(list_)

[1, 2, 3, 4, 5]


In [8]:
print(array_list)

[1 2 3 4 5]


##Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [10]:
for element in list_:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [12]:
for element in array_list:
  print(type(element))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


##Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [16]:
for element in array_list:
    print(type(element))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


##Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
arr = np.array([ [ 1 , 2 , 3, 4 ] , [ 4 , 5 , 6,7 ] ])

In [22]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [23]:
arr.shape

(2, 4)

In [24]:
arr.size

8

##Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [27]:
zeros_array = np.zeros((3, 3))

In [28]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
identity_matrix = np.eye(5)

In [30]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])